import 'package:blog_explorer/blogs/blog_home_screen/blog_home_screen_internet_error/blog_home_screen_internet_error_cubit.dart';
import 'package:blog_explorer/core/controllers/base_controller.dart';

class BlogHomeScreenInternetErrorController extends BaseController<BlogHomeScreenInternetErrorCubit>{}